# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from bilibili.vega.deneb.v1 import deneb_pb2 as bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2


class VegaDenebRPCStub(object):
    """
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MessagePulls = channel.unary_unary(
                '/bilibili.vega.deneb.v1.VegaDenebRPC/MessagePulls',
                request_serializer=bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2.MessagePullsReq.SerializeToString,
                response_deserializer=bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2.MessagePullsReply.FromString,
                )


class VegaDenebRPCServicer(object):
    """
    """

    def MessagePulls(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VegaDenebRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MessagePulls': grpc.unary_unary_rpc_method_handler(
                    servicer.MessagePulls,
                    request_deserializer=bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2.MessagePullsReq.FromString,
                    response_serializer=bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2.MessagePullsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilibili.vega.deneb.v1.VegaDenebRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VegaDenebRPC(object):
    """
    """

    @staticmethod
    def MessagePulls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bilibili.vega.deneb.v1.VegaDenebRPC/MessagePulls',
            bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2.MessagePullsReq.SerializeToString,
            bilibili_dot_vega_dot_deneb_dot_v1_dot_deneb__pb2.MessagePullsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
