"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import bilireq.grpc.protos.bilibili.app.distribution.v1.distribution_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class NightSettingsConfig(google.protobuf.message.Message):
    """"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_NIGHT_FOLLOW_SYSTEM_FIELD_NUMBER: builtins.int
    @property
    def is_night_follow_system(self) -> bilireq.grpc.protos.bilibili.app.distribution.v1.distribution_pb2.BoolValue:
        """"""
    def __init__(
        self,
        *,
        is_night_follow_system: bilireq.grpc.protos.bilibili.app.distribution.v1.distribution_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["is_night_follow_system", b"is_night_follow_system"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_night_follow_system", b"is_night_follow_system"]) -> None: ...

global___NightSettingsConfig = NightSettingsConfig
