# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bilireq.grpc.protos.bilibili/app/viewunite/pgcanymodel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(bilibili/app/viewunite/pgcanymodel.proto\x12\"bilibili.app.viewunite.pgcanymodel\"4\n\nViewPgcAny\x12\x11\n\tseason_id\x18\x01 \x01(\x04\x12\x13\n\x0bseason_type\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bilibili.app.viewunite.pgcanymodel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VIEWPGCANY']._serialized_start=80
  _globals['_VIEWPGCANY']._serialized_end=132
# @@protoc_insertion_point(module_scope)
